spring:
  application:
    name: spring-shell
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_shell_schema
    username: admin
    password: pass123
    name: spring_shell_schema
    driver-class-name: org.postgresql.Driver
  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
